services:
  flask-app:
    container_name: taco-boy-container-app
    build:
      context: .
      dockerfile: Dockerfile-dev
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
